# Generated by Django 5.0.4 on 2024-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.CharField(max_length=20)),
                ('productprice', models.CharField(max_length=10)),
                ('productquantity', models.CharField(max_length=50)),
                ('producttotal', models.CharField(max_length=20)),
                ('productname', models.CharField(max_length=20)),
            ],
        ),
    ]
